"""initial

Revision ID: 92df87fcac21
Revises: 
Create Date: 2019-05-31 15:46:27.011626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92df87fcac21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
